/**
 * Slide wishlist for "Presentación aleatoria". `query` is what we search on
 * Wikimedia Commons (English works best there); `caption` is shown to the
 * audience; `description` is what Jev sees when choosing (English).
 */
export interface SlideWish {
  id: string;
  query: string;
  caption: string;
  description: string;
}

export const SLIDE_WISHLIST: SlideWish[] = [
  { id: "gato-traje", query: "cat wearing suit tie", caption: "Un gato con traje y corbata", description: "A cat dressed in a suit and tie, looking like a businessman" },
  { id: "llama", query: "llama face close up", caption: "Una llama mirándote fijamente", description: "A llama staring straight into the camera" },
  { id: "astronauta", query: "Apollo astronaut moon surface", caption: "Un astronauta en la Luna", description: "An astronaut walking on the surface of the Moon" },
  { id: "titanic", query: "Titanic sinking painting", caption: "El Titanic hundiéndose", description: "The Titanic sinking in the ocean at night" },
  { id: "mapache", query: "raccoon garbage bin", caption: "Un mapache saqueando la basura", description: "A raccoon raiding a garbage bin" },
  { id: "oficina", query: "empty office cubicles", caption: "Una oficina de cubículos, vacía", description: "An empty open-plan office full of cubicles" },
  { id: "atasco", query: "traffic jam highway cars", caption: "Un atasco monumental", description: "A massive traffic jam on a highway" },
  { id: "pizza", query: "pizza margherita", caption: "Una pizza recién hecha", description: "A freshly baked pizza" },
  { id: "dinosaurio", query: "Tyrannosaurus skeleton museum", caption: "Un esqueleto de dinosaurio", description: "A T. rex skeleton in a museum" },
  { id: "paloma", query: "pigeon head close up", caption: "Una paloma con cara de pocos amigos", description: "A close-up of a pigeon with a grumpy look" },
  { id: "patito", query: "rubber duck yellow", caption: "Un patito de goma", description: "A yellow rubber duck" },
  { id: "perezoso", query: "sloth hanging tree", caption: "Un perezoso, sin prisa", description: "A sloth hanging lazily from a tree" },
  { id: "montana-rusa", query: "roller coaster loop", caption: "Una montaña rusa en pleno looping", description: "A roller coaster doing a loop" },
  { id: "dentista", query: "dentist chair", caption: "El sillón del dentista", description: "A dentist's chair in a clinic" },
  { id: "rueda", query: "flat tire car wheel", caption: "Una rueda pinchada", description: "A car with a flat tire" },
  { id: "tarta", query: "wedding cake white tiers", caption: "Una tarta de boda gigante", description: "A giant multi-tier wedding cake" },
  { id: "calabaza", query: "giant pumpkin contest", caption: "Una calabaza gigante de concurso", description: "A giant pumpkin at a competition" },
  { id: "sumo", query: "sumo wrestlers bout", caption: "Dos luchadores de sumo", description: "Two sumo wrestlers in a bout" },
  { id: "pinguinos", query: "emperor penguins colony", caption: "Una colonia de pingüinos", description: "A colony of emperor penguins" },
  { id: "despertador", query: "alarm clock twin bell", caption: "Un despertador antiguo", description: "An old-fashioned twin-bell alarm clock" },
  { id: "opera", query: "opera singer performing stage", caption: "Un cantante de ópera en pleno aria", description: "An opera singer performing dramatically on stage" },
  { id: "mimo", query: "mime whiteface performer", caption: "Un mimo actuando en la calle", description: "A street mime performing" },
  { id: "coliseo", query: "Colosseum Rome interior", caption: "El Coliseo de Roma", description: "The Colosseum in Rome" },
  { id: "volcan", query: "volcano eruption lava night", caption: "Un volcán en erupción", description: "A volcano erupting with lava" },
  { id: "lavanderia", query: "laundromat washing machines", caption: "Una lavandería de barrio", description: "A laundromat with rows of washing machines" },
  { id: "cola", query: "long queue people waiting", caption: "Una cola interminable", description: "A very long queue of people waiting" },
  { id: "ordenador", query: "IBM PC 1980s computer", caption: "Un ordenador de los años 80", description: "A 1980s personal computer" },
  { id: "cabras", query: "goats argan tree Morocco", caption: "Cabras subidas a un árbol", description: "Goats standing in the branches of a tree" },
  { id: "flamenco", query: "flamingo standing one leg", caption: "Un flamenco a la pata coja", description: "A flamingo standing on one leg" },
  { id: "nieve", query: "snowman winter", caption: "Un muñeco de nieve", description: "A snowman in winter" },
  { id: "ajedrez", query: "chess board pieces game", caption: "Una partida de ajedrez", description: "A chess board mid-game" },
  { id: "piscina", query: "crowded swimming pool summer", caption: "Una piscina abarrotada", description: "An extremely crowded public swimming pool" },
  { id: "papeleo", query: "stack of paperwork documents", caption: "Una montaña de papeleo", description: "A huge stack of paperwork and forms" },
  { id: "cactus", query: "saguaro cactus desert", caption: "Un cactus en el desierto", description: "A tall cactus in the desert" },
  { id: "papel", query: "toilet paper roll bathroom", caption: "Rollos de papel higiénico", description: "A stack of toilet paper rolls" },
  { id: "vaca", query: "Holstein cow head", caption: "Una vaca mirando a cámara", description: "A cow looking straight at the camera" },
  { id: "pirata", query: "pirate ship replica sailing", caption: "Un barco pirata", description: "A pirate ship under sail" },
  { id: "hamster", query: "hamster running wheel", caption: "Un hámster en su rueda", description: "A hamster running in a wheel" },
  { id: "playa", query: "tropical beach sunset palm", caption: "Un atardecer en el paraíso", description: "A tropical beach at sunset with palm trees" },
  { id: "carrito", query: "abandoned shopping cart", caption: "Un carrito de súper abandonado", description: "An abandoned shopping cart" },
  { id: "mosquito", query: "Aedes aegypti mosquito biting", caption: "Un mosquito, de cerca", description: "A close-up of a mosquito" },
  { id: "autobus", query: "yellow school bus", caption: "Un autobús escolar", description: "A yellow school bus" },
  { id: "cumple", query: "birthday party balloons cake children", caption: "Una fiesta de cumpleaños infantil", description: "A children's birthday party with balloons and cake" },
  { id: "cocodrilo", query: "crocodile mouth open", caption: "Un cocodrilo con la boca abierta", description: "A crocodile with its mouth wide open" },
  { id: "perro-gafas", query: "dog wearing sunglasses", caption: "Un perro con gafas de sol", description: "A dog wearing sunglasses" },
  { id: "ascensor", query: "elevator buttons panel", caption: "Los botones de un ascensor", description: "An elevator button panel" },
  { id: "reunion", query: "business meeting boardroom presentation", caption: "Una reunión de trabajo", description: "A boring corporate meeting in a boardroom" },
  { id: "cohete", query: "Space Shuttle launch", caption: "El lanzamiento de un cohete", description: "A rocket launching into space" },
  { id: "lluvia", query: "people umbrellas rain street", caption: "Una parada de autobús bajo la lluvia", description: "People waiting at a bus stop in the rain" },
  { id: "espagueti", query: "spaghetti bolognese plate", caption: "Un plato de espaguetis", description: "A plate of spaghetti" },
  { id: "barbero", query: "barber shop haircut", caption: "En la barbería", description: "A barber cutting a customer's hair" },
  { id: "bomberos", query: "fire truck red", caption: "Un camión de bomberos", description: "A red fire truck" },
  { id: "morsa", query: "walrus Odobenus rosmarus", caption: "Una morsa", description: "A walrus with big tusks" },
  { id: "helado", query: "dropped ice cream cone ground", caption: "Un helado caído al suelo", description: "An ice cream cone dropped on the ground" },
  { id: "gioconda", query: "Mona Lisa Leonardo da Vinci painting", caption: "La Gioconda", description: "The Mona Lisa painting" },
  { id: "grito", query: "The Scream Edvard Munch", caption: "El Grito, de Munch", description: "Edvard Munch's painting The Scream" },
  { id: "napoleon", query: "Napoleon Crossing the Alps David", caption: "Napoleón cruzando los Alpes", description: "Napoleon on a rearing horse crossing the Alps" },
  { id: "gato-caja", query: "cat inside cardboard box", caption: "Un gato en una caja", description: "A cat sitting inside a cardboard box" },
  { id: "maraton", query: "marathon runners crowd start", caption: "Corredores de maratón", description: "A crowd of marathon runners" },
  { id: "desguace", query: "car junkyard scrap", caption: "Un desguace de coches", description: "A junkyard full of wrecked cars" },
  { id: "globos", query: "hot air balloon festival", caption: "Globos aerostáticos", description: "Hot air balloons at a festival" },
  { id: "sushi", query: "sushi platter", caption: "Una bandeja de sushi", description: "A platter of sushi" },
  { id: "tiburon", query: "great white shark", caption: "Un tiburón blanco", description: "A great white shark" },
  { id: "camellos", query: "camel caravan desert dunes", caption: "Camellos en el desierto", description: "A camel caravan crossing desert dunes" },
  { id: "alpaca", query: "alpaca funny haircut", caption: "Una alpaca con un peinado ridículo", description: "An alpaca with a ridiculous hairstyle" },
  { id: "escaleras", query: "escalator shopping mall", caption: "Unas escaleras mecánicas", description: "Escalators in a shopping mall" },
  { id: "jubilados", query: "elderly couple dancing", caption: "Una pareja de jubilados bailando", description: "An elderly couple dancing" },
  { id: "tractor", query: "tractor farm field", caption: "Un tractor", description: "A tractor in a farm field" },
  { id: "cerdo", query: "pig mud wallowing", caption: "Un cerdo feliz en el barro", description: "A pig wallowing happily in mud" },
  { id: "tortuga", query: "Galapagos giant tortoise", caption: "Una tortuga gigante", description: "A giant tortoise" },
  { id: "karaoke", query: "karaoke singing microphone", caption: "Noche de karaoke", description: "Someone singing karaoke with a microphone" },
  { id: "bano-portatil", query: "portable toilets row festival", caption: "Baños portátiles de festival", description: "A row of portable toilets at a festival" },
  { id: "pato-patos", query: "ducklings following mother duck", caption: "Una familia de patos", description: "Ducklings following their mother in a line" },
  { id: "banana", query: "banana peel on floor", caption: "Una piel de plátano en el suelo", description: "A banana peel on the floor" },
  { id: "avion-cabina", query: "airplane cabin passengers economy", caption: "La cabina de un avión", description: "A crowded economy-class airplane cabin" },
  { id: "gimnasio", query: "gym weights dumbbells rack", caption: "Un gimnasio", description: "A gym with racks of dumbbells" },
  { id: "boda", query: "wedding couple ceremony", caption: "Una boda", description: "A couple at their wedding ceremony" },
  { id: "examen", query: "students exam hall", caption: "Un examen", description: "Students taking an exam in a big hall" },
  { id: "pulpo", query: "octopus underwater", caption: "Un pulpo", description: "An octopus underwater" },
  { id: "nube-tormenta", query: "thunderstorm lightning city", caption: "Una tormenta eléctrica", description: "A thunderstorm with lightning over a city" },
];
