/**
 * Vocabulary for "Ilustrador automático": each doodle is an emoji Jev can
 * choose to draw, with a Spanish label (handwritten under it) and an
 * English description (what Jev matches against the speech).
 */
export interface Doodle {
  /** Stable id (historically the lucide icon name). */
  id: string;
  /** What is drawn on the board. */
  emoji: string;
  label: string;
  description: string;
}

export const DOODLES: Doodle[] = [
  { id: "Sun", emoji: "☀️", label: "sol", description: "sun, sunny day, heat, summer, morning" },
  { id: "Moon", emoji: "🌙", label: "luna", description: "night, moon, sleep time, late" },
  { id: "CloudRain", emoji: "🌧️", label: "lluvia", description: "rain, bad weather, gloomy day" },
  { id: "Snowflake", emoji: "❄️", label: "frío", description: "snow, cold, winter, freezing" },
  { id: "Zap", emoji: "⚡", label: "¡zas!", description: "lightning, shock, sudden surprise, electricity, energy" },
  { id: "Flame", emoji: "🔥", label: "fuego", description: "fire, burning, passion, disaster, spicy" },
  { id: "Waves", emoji: "🌊", label: "mar", description: "sea, ocean, beach, swimming, waves, water" },
  { id: "Mountain", emoji: "⛰️", label: "montaña", description: "mountain, hiking, climbing, big challenge" },
  { id: "TreePine", emoji: "🌲", label: "árbol", description: "forest, tree, nature, countryside, camping" },
  { id: "Palmtree", emoji: "🌴", label: "playa", description: "tropical, holidays, palm tree, paradise" },
  { id: "Heart", emoji: "❤️", label: "amor", description: "love, romance, affection, someone dear, passion" },
  { id: "HeartCrack", emoji: "💔", label: "corazón roto", description: "heartbreak, breakup, sadness, loss, disappointment" },
  { id: "Star", emoji: "⭐", label: "estrella", description: "star, excellence, fame, wish, the best" },
  { id: "Trophy", emoji: "🏆", label: "trofeo", description: "winning, victory, championship, award, success" },
  { id: "Skull", emoji: "💀", label: "muerte", description: "death, danger, disaster, something went terribly wrong, poison" },
  { id: "Ghost", emoji: "👻", label: "fantasma", description: "ghost, fear, horror, spooky, haunted" },
  { id: "Cake", emoji: "🎂", label: "tarta", description: "birthday, celebration, cake, party, anniversary" },
  { id: "Gift", emoji: "🎁", label: "regalo", description: "gift, present, surprise, generosity, christmas" },
  { id: "PartyPopper", emoji: "🎉", label: "fiesta", description: "party, celebration, confetti, going out, fun night" },
  { id: "Camera", emoji: "📸", label: "foto", description: "photo, camera, memories, selfie, tourism" },
  { id: "Book", emoji: "📖", label: "libro", description: "book, reading, studying, story, library" },
  { id: "GraduationCap", emoji: "🎓", label: "estudios", description: "school, university, exam, graduation, learning" },
  { id: "Laptop", emoji: "💻", label: "ordenador", description: "computer, laptop, work, coding, office, internet" },
  { id: "Phone", emoji: "📱", label: "teléfono", description: "phone call, mobile phone, messages, someone calling" },
  { id: "Mail", emoji: "✉️", label: "mensaje", description: "email, letter, message, notification, news" },
  { id: "Gamepad2", emoji: "🎮", label: "videojuego", description: "video games, gaming, playing, console" },
  { id: "Tv", emoji: "📺", label: "tele", description: "television, series, watching, news, screen" },
  { id: "Bed", emoji: "🛏️", label: "cama", description: "sleeping, bed, tired, laziness, dreams, waking up" },
  { id: "Clock", emoji: "⏰", label: "hora", description: "time, being late, hurry, waiting, schedule, hours" },
  { id: "Hourglass", emoji: "⏳", label: "espera", description: "waiting, patience, deadline, time running out" },
  { id: "Calendar", emoji: "📅", label: "fecha", description: "a date, a day, an appointment, the calendar, a year" },
  { id: "Map", emoji: "🗺️", label: "mapa", description: "getting lost, directions, journey, map, exploring" },
  { id: "Globe", emoji: "🌍", label: "mundo", description: "the world, countries, abroad, travel, international" },
  { id: "Baby", emoji: "👶", label: "bebé", description: "baby, childhood, being little, kids, birth" },
  { id: "Users", emoji: "👥", label: "gente", description: "people, crowd, friends, group, audience, family" },
  { id: "Handshake", emoji: "🤝", label: "trato", description: "agreement, deal, meeting someone, negotiation, friendship" },
  { id: "Dog", emoji: "🐶", label: "perro", description: "dog, pet, loyalty, walking the dog" },
  { id: "Cat", emoji: "🐱", label: "gato", description: "cat, pet, independence, laziness" },
  { id: "Bird", emoji: "🐦", label: "pájaro", description: "bird, flying, freedom, pigeon, singing" },
  { id: "Fish", emoji: "🐟", label: "pez", description: "fish, fishing, sea creature, aquarium" },
  { id: "Bug", emoji: "🐛", label: "bicho", description: "insect, mosquito, bug, something annoying, glitch" },
  { id: "Rabbit", emoji: "🐰", label: "conejo", description: "rabbit, speed, magic trick, easter" },
  { id: "Turtle", emoji: "🐢", label: "tortuga", description: "slowness, patience, taking it easy, old age" },
  { id: "PawPrint", emoji: "🐾", label: "animal", description: "animals in general, zoo, wild, tracks" },
  { id: "Pizza", emoji: "🍕", label: "pizza", description: "pizza, fast food, dinner with friends, hunger" },
  { id: "Coffee", emoji: "☕", label: "café", description: "coffee, breakfast, waking up, a break, a chat" },
  { id: "Beer", emoji: "🍺", label: "cerveza", description: "beer, bar, drinks, going out, cheers" },
  { id: "Wine", emoji: "🍷", label: "vino", description: "wine, dinner, elegance, celebration, romance" },
  { id: "Utensils", emoji: "🍽️", label: "comida", description: "food, eating, restaurant, cooking, meal" },
  { id: "IceCreamCone", emoji: "🍦", label: "helado", description: "ice cream, summer treat, childhood, sweet" },
  { id: "Apple", emoji: "🍎", label: "fruta", description: "fruit, health, diet, apple, teacher" },
  { id: "ShoppingCart", emoji: "🛒", label: "compras", description: "shopping, supermarket, buying, spending" },
  { id: "Banknote", emoji: "💵", label: "dinero", description: "money, salary, rich, expensive, paying" },
  { id: "PiggyBank", emoji: "🐷", label: "ahorro", description: "savings, being cheap, budget, poverty, saving up" },
  { id: "Briefcase", emoji: "💼", label: "trabajo", description: "job, work, boss, office, career, meeting" },
  { id: "Hammer", emoji: "🔨", label: "obra", description: "building, fixing, DIY, tools, hard work" },
  { id: "Key", emoji: "🔑", label: "llave", description: "keys, locked out, home, secret, solution" },
  { id: "Lock", emoji: "🔒", label: "secreto", description: "secret, privacy, locked, security, password" },
  { id: "Shield", emoji: "🛡️", label: "protección", description: "protection, defense, safety, insurance, police" },
  { id: "Sword", emoji: "⚔️", label: "espada", description: "fight, battle, conflict, argument, competition" },
  { id: "Crown", emoji: "👑", label: "corona", description: "king, queen, being the boss, royalty, ego, winning" },
  { id: "Rocket", emoji: "🚀", label: "cohete", description: "rocket, space, launch, ambition, fast growth" },
  { id: "Brain", emoji: "🧠", label: "cerebro", description: "thinking, idea, intelligence, memory, mind" },
  { id: "Lightbulb", emoji: "💡", label: "idea", description: "an idea, realisation, invention, eureka" },
  { id: "HelpCircle", emoji: "❓", label: "¿?", description: "doubt, question, confusion, not knowing" },
  { id: "AlertTriangle", emoji: "⚠️", label: "peligro", description: "warning, danger, mistake, careful, risk" },
  { id: "Bomb", emoji: "💣", label: "bomba", description: "explosion, catastrophe, drama, big trouble" },
  { id: "Eye", emoji: "👁️", label: "ojo", description: "seeing, watching, being watched, attention, looking" },
  { id: "Ear", emoji: "👂", label: "oreja", description: "listening, hearing, gossip, noise" },
  { id: "Hand", emoji: "✋", label: "mano", description: "hand, help, stop, touching, greeting" },
  { id: "Footprints", emoji: "👣", label: "pasos", description: "walking, journey, steps, running away, path" },
  { id: "Umbrella", emoji: "☂️", label: "paraguas", description: "umbrella, rain, protection, forgetting things" },
  { id: "Thermometer", emoji: "🤒", label: "fiebre", description: "illness, fever, temperature, being sick" },
  { id: "Pill", emoji: "💊", label: "medicina", description: "medicine, doctor, hospital, healing, pills" },
  { id: "Stethoscope", emoji: "🩺", label: "médico", description: "doctor, hospital, health check, nurse" },
  { id: "Dumbbell", emoji: "🏋️", label: "gimnasio", description: "gym, exercise, strength, fitness, sport" },
  { id: "Medal", emoji: "🏅", label: "medalla", description: "medal, achievement, race, competition, pride" },
  { id: "Flag", emoji: "🏁", label: "meta", description: "finish line, goal, country, flag, milestone" },
  { id: "Megaphone", emoji: "📣", label: "grito", description: "shouting, announcement, protest, loud" },
  { id: "Mic", emoji: "🎤", label: "micro", description: "speaking in public, microphone, singing, stage" },
  { id: "Music", emoji: "🎵", label: "música", description: "music, song, concert, dancing, singing" },
  { id: "Guitar", emoji: "🎸", label: "guitarra", description: "guitar, band, playing music, rock" },
  { id: "Car", emoji: "🚗", label: "coche", description: "car, driving, traffic, road trip, parking" },
  { id: "Bus", emoji: "🚌", label: "autobús", description: "bus, public transport, commuting, missing the bus" },
  { id: "Plane", emoji: "✈️", label: "avión", description: "airplane, flight, airport, travel abroad" },
  { id: "Train", emoji: "🚆", label: "tren", description: "train, station, commuting, journey" },
  { id: "Ship", emoji: "🚢", label: "barco", description: "ship, boat, cruise, sailing, sea trip" },
  { id: "Bike", emoji: "🚲", label: "bici", description: "bicycle, cycling, falling off a bike, exercise" },
  { id: "Building2", emoji: "🏙️", label: "ciudad", description: "city, buildings, downtown, apartment, urban" },
  { id: "Home", emoji: "🏠", label: "casa", description: "home, house, family home, moving, living" },
  { id: "Store", emoji: "🏪", label: "tienda", description: "shop, store, market, small business" },
  { id: "Church", emoji: "⛪", label: "iglesia", description: "church, wedding, religion, tradition" },
  { id: "Tent", emoji: "⛺", label: "camping", description: "camping, tent, outdoors, survival" },
  { id: "Ticket", emoji: "🎟️", label: "entrada", description: "ticket, cinema, concert, event, queue" },
  { id: "Popcorn", emoji: "🍿", label: "cine", description: "movies, cinema, popcorn, watching a film" },
  { id: "Drama", emoji: "🎭", label: "teatro", description: "theatre, acting, drama, pretending, masks" },
  { id: "Gavel", emoji: "⚖️", label: "juez", description: "judge, law, court, rules, verdict, punishment" },
  { id: "Puzzle", emoji: "🧩", label: "puzle", description: "puzzle, problem solving, complicated, pieces fitting" },
  { id: "Dice5", emoji: "🎲", label: "suerte", description: "luck, chance, gambling, random, risk" },
  { id: "Sparkles", emoji: "✨", label: "magia", description: "magic, wonder, something amazing, sparkle" },
  { id: "Smile", emoji: "😊", label: "sonrisa", description: "happiness, smiling, joy, good mood" },
  { id: "Frown", emoji: "😢", label: "pena", description: "sadness, disappointment, bad mood, crying" },
  { id: "Angry", emoji: "😡", label: "enfado", description: "anger, rage, frustration, arguing" },
  { id: "Laugh", emoji: "😂", label: "risa", description: "laughing, joke, funny moment, comedy" },
  { id: "ThumbsUp", emoji: "👍", label: "bien", description: "approval, good, agreement, success, yes" },
  { id: "ThumbsDown", emoji: "👎", label: "mal", description: "disapproval, bad, failure, no, rejection" },
  { id: "Glasses", emoji: "👓", label: "gafas", description: "glasses, reading, nerd, seeing clearly, disguise" },
  { id: "Shirt", emoji: "👕", label: "ropa", description: "clothes, fashion, dressing up, laundry, shirt" },
  { id: "Watch", emoji: "⌚", label: "reloj", description: "wristwatch, punctuality, luxury, time" },
  { id: "Bath", emoji: "🛁", label: "baño", description: "bathroom, shower, bath, toilet, hygiene" },
  { id: "Sofa", emoji: "🛋️", label: "sofá", description: "sofa, relaxing, couch, netflix, laziness" },
  { id: "Scissors", emoji: "✂️", label: "tijeras", description: "cutting, haircut, scissors, crafts" },
  { id: "Anchor", emoji: "⚓", label: "ancla", description: "anchor, stability, stuck, port, navy" },
  { id: "Award", emoji: "🥇", label: "premio", description: "prize, recognition, award, honour" },
  { id: "Target", emoji: "🎯", label: "objetivo", description: "goal, target, focus, aim, plan" },
  { id: "Egg", emoji: "🥚", label: "huevo", description: "egg, breakfast, fragile, beginning, chicken" },
  { id: "Croissant", emoji: "🥐", label: "desayuno", description: "breakfast, bakery, pastry, France, morning" },
  { id: "Candy", emoji: "🍬", label: "caramelo", description: "candy, sweets, sugar, treat, children" },
  { id: "Carrot", emoji: "🥕", label: "zanahoria", description: "vegetables, diet, garden, rabbit food, healthy" },
  { id: "Banana", emoji: "🍌", label: "plátano", description: "banana, slipping, monkey, fruit" },
  { id: "Feather", emoji: "🪶", label: "pluma", description: "lightness, feather, writing, bird, softness" },
  { id: "Wind", emoji: "💨", label: "viento", description: "wind, storm, air, blowing away" },
  { id: "Rainbow", emoji: "🌈", label: "arcoíris", description: "rainbow, hope, after the storm, colour, happiness" },
  { id: "Tornado", emoji: "🌪️", label: "tornado", description: "chaos, tornado, everything spinning, disaster" },
  { id: "Ambulance", emoji: "🚑", label: "ambulancia", description: "emergency, ambulance, accident, hospital rush" },
  { id: "Siren", emoji: "🚨", label: "alarma", description: "alarm, police, emergency, warning siren" },
  { id: "Bell", emoji: "🔔", label: "campana", description: "bell, notification, school bell, church bell, alarm" },
  { id: "Wallet", emoji: "👛", label: "cartera", description: "wallet, losing the wallet, paying, cards" },
  { id: "Landmark", emoji: "🏦", label: "banco", description: "bank, government, institution, official building" },
  { id: "Headphones", emoji: "🎧", label: "auriculares", description: "headphones, podcast, listening to music, ignoring people" },
  { id: "MessageCircle", emoji: "💬", label: "charla", description: "conversation, chatting, talking, gossip" },
  { id: "Timer", emoji: "⏱️", label: "cronómetro", description: "timer, countdown, running out of time, speed" },
  { id: "Wand2", emoji: "🪄", label: "varita", description: "magic wand, wish, fantasy, wizard" },
  { id: "Swords", emoji: "🤺", label: "duelo", description: "duel, rivalry, fight, competition" },

  // --- Reactions: what the audience is thinking. Only funny when used with a wink. ---
  { id: "EyesRoll", emoji: "🙄", label: "ya…", description: "REACTION: the audience rolls its eyes — an excuse, a cliché, 'as I always say', predictable" },
  { id: "Clown", emoji: "🤡", label: "circo", description: "REACTION: this is getting ridiculous, a clownish situation, someone made a fool of themselves" },
  { id: "Facepalm", emoji: "🤦", label: "ay…", description: "REACTION: facepalm — an obvious mistake, a bad decision the speaker admits, 'why did I do that'" },
  { id: "RedFlag", emoji: "🚩", label: "alerta roja", description: "REACTION: red flag — a warning sign in a relationship, job or plan that the speaker ignored" },
  { id: "Liar", emoji: "🤥", label: "sí, claro", description: "REACTION: that is probably not true, a suspicious claim, a too-good story" },
  { id: "Sleepy", emoji: "😴", label: "zzz", description: "REACTION: boring part, long explanation, the audience is dozing off, a slow story" },
  { id: "TinyViolin", emoji: "🎻", label: "violín", description: "REACTION: tiny violin — the speaker is asking for pity over a small problem, melodrama" },
  { id: "Goat", emoji: "🐐", label: "el mejor", description: "REACTION: the greatest of all time — the speaker is bragging or praising someone as the best" },
  { id: "MindBlown", emoji: "🤯", label: "boom", description: "REACTION: mind blown — a surprising fact, a plot twist, an unexpected revelation" },
  { id: "Detective", emoji: "🕵️", label: "sospechoso", description: "REACTION: something does not add up, a suspicious detail, an investigation, a secret" },
  { id: "Unicorn", emoji: "🦄", label: "unicornio", description: "REACTION: fantasy — an impossible dream, unrealistic plan, 'someday I will…'" },
  { id: "Moai", emoji: "🗿", label: "…", description: "REACTION: stone face — awkward silence, deadpan, an anticlimax, nobody laughed" },
  { id: "Popcorn", emoji: "🍿", label: "palomitas", description: "REACTION: drama incoming — gossip, a conflict about to be told, the audience settles in" },
  { id: "MoneyFlying", emoji: "💸", label: "adiós dinero", description: "REACTION: money flying away — an expensive mistake, wasted money, a bad purchase" },
  { id: "Halo", emoji: "😇", label: "angelito", description: "REACTION: playing innocent — 'it wasn't me', suspiciously good behaviour" },
  { id: "Grimace", emoji: "😬", label: "uf", description: "REACTION: awkward moment, cringe, an embarrassing confession, 'yikes'" },
  { id: "Sweat", emoji: "🥲", label: "risa nerviosa", description: "REACTION: smiling through pain — bittersweet, laughing to not cry, a small tragedy" },
  { id: "Pray", emoji: "🙏", label: "por favor", description: "REACTION: begging, hoping, 'please let it work', gratitude" },
  { id: "Eyes", emoji: "👀", label: "¿en serio?", description: "REACTION: 'are you serious?', a scandalous detail, the audience side-eyes" },
  { id: "Circus", emoji: "🎪", label: "qué circo", description: "REACTION: total chaos, a circus of a situation, everything going wrong at once" },
  { id: "UFO", emoji: "🛸", label: "ovni", description: "REACTION: the story went somewhere far-fetched, out of this world, unbelievable" },
  { id: "Nerd", emoji: "🤓", label: "empollón", description: "REACTION: technical detail, showing off knowledge, 'actually…'" },
  { id: "Shush", emoji: "🤫", label: "shh", description: "REACTION: a secret is being told, 'don't tell anyone', confidential" },
  { id: "Poop", emoji: "💩", label: "desastre", description: "REACTION: it all went to hell, a total mess, a terrible result" },
  { id: "Sunglasses", emoji: "😎", label: "crack", description: "REACTION: the speaker thinks they were cool, a smooth move, showing off" },
];

export const DOODLE_IDS = new Set(DOODLES.map((d) => d.id));

/** Marker colours Jev can pick, by emotional tone. */
export const MARKERS: { id: string; description: string; color: string }[] = [
  { id: "negro", description: "neutral, serious, factual", color: "#1f1a17" },
  { id: "rojo", description: "passion, anger, danger, love, intensity", color: "#d2322d" },
  { id: "azul", description: "calm, sadness, water, cold, thinking", color: "#2b5fbf" },
  { id: "verde", description: "nature, money, health, hope, envy", color: "#2f8f4e" },
  { id: "naranja", description: "joy, energy, fun, warmth, surprise", color: "#e4761b" },
  { id: "morado", description: "mystery, magic, dreams, drama, night", color: "#7b3fbf" },
];
